version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: crm_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: crm_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend